### PR TITLE
Bug/update deps

### LINKED ISSUE #39: Breaking changes on getstream-js dependency
gestream-js had a braking changes since version 5.0.0 https://github.com/GetStream/stream-js/blob/master/CHANGELOG.md#500---2020-07-06

Now when require('getstream-node') it is throwing an exception for missing function connect: "stream.connect is not a function".

Thanks

### PR DESCRIPTION
**Pull request by mahboubii**
fixes #39

### CODE REVIEW

File: src/FeedManager.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-var stream = require('getstream'),
+var stream = require('getstream').default,
```
Comment (ferhatelmas) [inline src/FeedManager.js:1]: how about using `import` ? A separate PR ?

Comment (mahboubii) [reply src/FeedManager.js:1]: yea out of this PR's concern, refactoring this lib to ES6 is a bit of work

Comment (ferhatelmas) [reply src/FeedManager.js:1]: I thought so but better to point.
